spring.application.name=rental
spring.datasource.url=jdbc:mysql://localhost:3306/rental-store
server.port=8081
spring.datasource.username=root
spring.datasource.password=Pass@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
